version: '3.8'
networks:
  api_server_default:
    external: true
services:
  smartduelserver:
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
      - 52300:52300
